name: Build QMK
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build QMK
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        repository: [filterpaper/qmk_firmware]
        branch: [develop, sym_defer_g_bool, sym_defer_g_uint8]

    steps:
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: ${{ matrix.repository }}
        ref: ${{ matrix.branch }}
        submodules: true

    - name: Setup safe directory
      run: git config --global --add safe.directory '*'

    - name: Compile
      run: qmk compile -kb a_dux -km default

  purge:
    uses: filterpaper/scripts/.github/workflows/purge-workflow.yml@main
    with:
      purge-age: 5
      delete-all-completed: false
      delete-all-incomplete: true
